fix github action benchmark rustup not found
parcel-bundler/parcel pull request #6298
Opened 2021-05-17 18:55 UTC by Magi-KS

GitHub Action benchmark is failing, this PR is attempt at fixing it.

turns out GitHub Action executes shell script in non-interactive mode, so .bashrc is not loaded by default.
https://github.community/t/self-hosted-not-using-bashrc/18358

2021-05-17 19:03 UTC, DeMoorJasper approved these changes

2021-05-18 16:38 UTC, DeMoorJasper requested changes
approved this a bit too quickly, doesn't fix the benchmark

2021-05-19 20:48 UTC, Magi-KS commented
changes here are not needed.
fixes over at https://github.com/parcel-bundler/parcel-benchmark-action/pull/37

2021-05-19 22:00 UTC, closed without merging

2021-05-19 22:00 UTC, DeMoorJasper commented
Thanks for looking into this and fixing the benchmark